package bwie.com.weidumall.green;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import bwie.com.weidumall.entity.cart.SysnGoods;

import bwie.com.weidumall.green.SysnGoodsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sysnGoodsDaoConfig;

    private final SysnGoodsDao sysnGoodsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sysnGoodsDaoConfig = daoConfigMap.get(SysnGoodsDao.class).clone();
        sysnGoodsDaoConfig.initIdentityScope(type);

        sysnGoodsDao = new SysnGoodsDao(sysnGoodsDaoConfig, this);

        registerDao(SysnGoods.class, sysnGoodsDao);
    }
    
    public void clear() {
        sysnGoodsDaoConfig.clearIdentityScope();
    }

    public SysnGoodsDao getSysnGoodsDao() {
        return sysnGoodsDao;
    }

}
